### ISSUE TITLE
Doorschuiven van een speler na hogere groep na start nieuwe periode werkt niet goed

### ISSUE THREAD

**Issue by oxygenius** [lmeulen/IJC_UI#15]
De speler wordt wel uit de lijst met aanwezige spelers gehaald en komt ook bij de nieuwe groep erbij, maar de spelers die spelen lijst en de wedstrijden worden niet aangepast.
P.S.: Herstart v.d. applicatie corrigeert het.

![issue 15](https://cloud.githubusercontent.com/assets/4378315/20487196/b03a64f2-b002-11e6-9ac7-a2269659d49f.jpg)

**Comment by lmeulen** [comment]
Mogelijk alleen een interface issue. Als je wisselt van tabblad en teruggaat, wordt het dan correct getoond?

**Comment by oxygenius** [comment]
Nee. Heropstarten is noodzakelijk,

**Comment by lmeulen** [comment]
Heb je voro mij een status/configuratie die deze fout laat zien? Dus voor het starten van de nieuwe ronde en welke speler moet ik dan af/aanmelden?

**Comment by oxygenius** [comment]
Ga ik voor zorgen.



Verzonden vanaf mijn Samsung Galaxy-smartphone.

-------- Oorspronkelijk bericht --------
Van: Leo van der Meulen <notifications@github.com>
Datum: 25-11-16 13:34 (GMT+01:00)
Aan: lmeulen/IJC_UI <IJC_UI@noreply.github.com>
Cc: Lars Dam <l.p.dam@amity.nl>, Author <author@noreply.github.com>
Onderwerp: Re: [lmeulen/IJC_UI] Bug: Doorschuiven van een speler na hogere groep na start nieuwe periode werkt niet goed (#15)


Heb je voro mij een status/configuratie die deze fout laat zien? Dus voor het starten van de nieuwe ronde en welke speler moet ik dan af/aanmelden?
