### ISSUE TITLE
Volgorde nieuwe periode?

### ISSUE THREAD

**Issue by oxygenius** [lmeulen/IJC_UI#17]
Als een nieuwe periode begint is het dan slim automatisch te sorteren op rating? Want de volgorde die overblijft na doorschuiven is 'fictief' op basis van de stand van de vorige periode.
Na éénmaal handmatig sorteren op rating is de oude situatie ook niet terug te halen. Wat kwa reproduceerbaarheid niet praktisch is.

**Comment by lmeulen** [comment]
Goed idee, aangepast.
