### ISSUE TITLE
Bewerken speelschema

### ISSUE THREAD

**Issue by oxygenius** [lmeulen/IJC_UI#18]
Bug: Bij het bewerken van het speelschema, loop ik tegen problemen aan. Serie 1 lijkt goed te gaan. Serie 2 levert wat problemen op. Maar trio is grootste probleem.
Als alle wedstrijden worden verwijderd, kan alleen nog maar één wedstrijd worden toegevoegd. Met geen mogelijkheid te herstellen, behalve nieuwe indeling maken.

**Comment by lmeulen** [comment]
Wat ik probeer is: een wedstrijdindeling maken, drie keer op wis drukken. Ik kan dan gewoon nieuwe wedstrijden toevoegen. 
Heb je voor mij een status.json, onfiguratie.json en een stappenplannetje om het te reconstrueren?

**Comment by oxygenius** [comment]
Ja stuur ik.



Verzonden vanaf mijn Samsung Galaxy-smartphone.

-------- Oorspronkelijk bericht --------
Van: Leo van der Meulen <notifications@github.com>
Datum: 25-11-16 14:54 (GMT+01:00)
Aan: lmeulen/IJC_UI <IJC_UI@noreply.github.com>
Cc: Lars Dam <l.p.dam@amity.nl>, Author <author@noreply.github.com>
Onderwerp: Re: [lmeulen/IJC_UI] BUG: Bewerken speelschema (#18)


Wat ik probeer is: een wedstrijdindeling maken, drie keer op wis drukken. Ik kan dan gewoon nieuwe wedstrijden toevoegen.
Heb je voor mij een status.json, onfiguratie.json en een stappenplannetje om het te reconstrueren?
