### ISSUE TITLE
BUG: Sorteren in Aanwezigeheidstabel

### ISSUE THREAD

**Issue by oxygenius** [lmeulen/IJC_UI#20]
Sorteren gebeurd op basis van de verkeerde kolom. 
Nu Initialen voor Rating en Rating voor Punten.
Ook zou handig zijn, dat als je nóg een keer klikt je ASC/DESC wisselt.

**Comment by lmeulen** [comment]
Beiden aangepast. Nu sorteren op de aangeklikte kolom en wisselend ASC / DESC.
