### ISSUE TITLE
Doorgeschoven spelers spelen tegen te zware spelers

### ISSUE THREAD

**Issue by lmeulen** [lmeulen/IJC_UI#40]
Als spelers doorschuiven naar een hogere groep, nemen ze hun punten mee uit hun huidige groep. Het kan voorkomen dat het aantal punten dat zij hebben, ondanks het startverschil van 10 punten, hoger is dan het aantal punten van de laagste spelers in de hogere groep.
In dit geval worden ze bij het indienen 'tussen' de gewone spelers van de groep geplaatst en spelen dus niet tegen de onderste spelers uit de hogere groep, maar gelijk tegen de middenmoot (of hoger).
In de bijlage een voorbeeld, waarbij het speelschema van de Lopergroep automatisch is bepaald en de doorgeschoven speler op nr 13 speelt tegen nummer 5 van de Lopergroep.

Er moet een oplossing gezocht worden waarbij de doorgeschoven spelers altijd onder de niet doorgeschoven spelers terecht komen.

[status.zip](https://github.com/lmeulen/IJC_UI/files/1383395/status.zip)

**Comment by lmeulen** [comment]
In het meegeleverde voorbeeld speelt in de Damegroep een doorschuiver (pos 13) zelfs tegen de koploper.

**Comment by lmeulen** [comment]
Dit is de handmatig ingedeelde groepsindeling
[status_hand.zip](https://github.com/lmeulen/IJC_UI/files/1383526/status_hand.zip)

**Comment by oxygenius** [comment]
Indeling is verbeterd. Issue is niet meer gesignaleerd
