### ISSUE TITLE
Zelfde wedstrijd eerste en tweede ronde

### ISSUE THREAD

**Issue by lmeulen** [lmeulen/IJC_UI#45]
Met bijbehorende status en configuratie wordt er in de laagste groep een zelfde wedstrijd gegenereerd in de eerste en de tweede speelronde
[issue45.zip](https://github.com/lmeulen/IJC_UI/files/1502295/issue45.zip)

**Comment by oxygenius** [comment]
Lijkt me verholpen.

**Comment by lmeulen** [comment]
Gesloten, niet meer reproduceerbaar.
