### ISSUE TITLE
BUG? - Aanpassen Witvoorkeur bij Bewerken speler werkt niet

### ISSUE THREAD

**Issue by oxygenius** [lmeulen/IJC_UI#6]
Als een speler bewerkt wordt dat wordt de aangepaste witvoorkeur niet opgeslagen.

**Comment by lmeulen** [comment]
Dit veld werd inderdaad niet opgeslagen, is nu aangepast

**Comment by oxygenius** [comment]
Top

Verzonden vanaf mijn Samsung Galaxy-smartphone.

-------- Oorspronkelijk bericht --------
Van: Leo van der Meulen notifications@github.com
Datum: 12-11-16 11:22 (GMT+01:00)
Aan: lmeulen/IJC_UI IJC_UI@noreply.github.com
Cc: Lars Dam l.p.dam@amity.nl, Author author@noreply.github.com
Onderwerp: Re: [lmeulen/IJC_UI] BUG? - Aanpassen Witvoorkeur bij Bewerken speler werkt niet (#6)

Dit veld werd inderdaad niet opgeslagen, is nu aangepast
