### ISSUE TITLE
Request - Uitslagen / Stand

### ISSUE THREAD

**Issue by oxygenius** [lmeulen/IJC_UI#7]
Ik denk dat het handig zou zijn om de huidige uitslag bestanden wat eigenlijk de laatste stand bevat te hernoemen. Dus i.p.v. Rx-yUitslag.txt moet dit zijn Rx-yStand.txt
Daarnaast een bestand te genereren voor de werkelijke uitslagen. Die moet er dan wat mij betreft uit komen te zien als Rx-y Indeling.xls of Rx-yWedstrijden.txt maar dan natuurlijk Rx-yUitslagen heten.

**Comment by lmeulen** [comment]
Westrijduitslagen worden nu in Rx-yUitslag.txt weggeschreven.
Standen worden nu in Rx-yStand[-long].txt  weggeschreven.

**Comment by oxygenius** [comment]
Hoi Leo,

Heerlijk dit. ;-)

Met vriendelijke groet,

Lars Dam
Manager ICT diensten
[cid:image001.png@01D23E5E.5B9BC9B0]
Amity ict solutions
Jan van Embdenweg 61
6861 ZS Oosterbeek
+31(0)30-6021710
http://www.amity.nlhttp://www.amity.nl/
Kaspersky Silver Partnerhttp://send.onenetworkdirect.net/z/313446/CD153808/ / Kaspersky Retail Partner
BTW: NL170826831B01 / KvK: 30101926

Van: Leo van der Meulen [mailto:notifications@github.com]
Verzonden: zaterdag 12 november 2016 16.04
Aan: lmeulen/IJC_UI
CC: Lars Dam; Author
Onderwerp: Re: [lmeulen/IJC_UI] Request - Uitslagen / Stand (#7)

Westrijduitslagen worden nu in Rx-yUitslag.txt weggeschreven.
Standen worden nu in Rx-yStand[-long].txt weggeschreven.
