### ISSUE TITLE
Zwart/wit voorkeur

### ISSUE THREAD

**Issue by lmeulen** [lmeulen/IJC_UI#8]
De zwart/wit voorkeur van spelers neigt niet goed naar een neutrale stand. Er zijn te veel spelers met een voorkeur van +2 of -2 en dit moet kunnen verbeteren.

**Comment by lmeulen** [comment]
Na elke speelronde worden de spelers ge-update: groep = updateSpelers(groep, serie);. Dit gebeurt voor zowel de klassieke (GroepenIndeler:369) als de Fuzzy indeling (GroepenIndelerFuzzy:213).
In deze methode wordt de witvoorkeur voor elke speler bijgewerkt, waarbij 1.1 als verhoging/verlaging wordt gebruikt om waar mogelijk de tweede wedstrijd met een andere kleur te spelen. 
Dit lijkt allemaal correct, maar voldoet schijnbaar nog niet.

**Comment by oxygenius** [comment]
Voor en na de Fuzzy routine heb ik een ZW balans check ingebouwd. Die lijkt vooralsnog gunstig:

INFO: ZW balans voor deze ronde is 14
nov 21, 2016 11:16:11 AM nl.detoren.ijc.ui.control.GroepenIndelerFuzzy maakWedstrijdenVoorGroep
INFO: ZW balans na deze ronde is 6

**Comment by oxygenius** [comment]
Bij verschillende pogingen heb ik alleen afname van de ZW balans geconstateerd geen toename.
Kan deze gesloten worden?

**Comment by lmeulen** [comment]
Geen reproduceerbaar slecht resultaat.
